// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzcZmF8_ZcAeVhSvbdASdmU0qgtdq47ak',
    appId: '1:549657351342:web:a53794cb04ec767bb3893f',
    messagingSenderId: '549657351342',
    projectId: 'digital-society-a2433',
    authDomain: 'digital-society-a2433.firebaseapp.com',
    storageBucket: 'digital-society-a2433.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKKwWUP_BOiIOJYd5QzPglWofN6yfPq9M',
    appId: '1:549657351342:android:c1fb798ff3700fdab3893f',
    messagingSenderId: '549657351342',
    projectId: 'digital-society-a2433',
    storageBucket: 'digital-society-a2433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeRa_xox25mkEVDUV9ocYe7byIwxf7wWI',
    appId: '1:549657351342:ios:5a91ea74df511264b3893f',
    messagingSenderId: '549657351342',
    projectId: 'digital-society-a2433',
    storageBucket: 'digital-society-a2433.appspot.com',
    iosClientId: '549657351342-tb5itbcovr5hokvsl2rbrsqg01dm3b4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalsociety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeRa_xox25mkEVDUV9ocYe7byIwxf7wWI',
    appId: '1:549657351342:ios:e11f0beaa9f9149eb3893f',
    messagingSenderId: '549657351342',
    projectId: 'digital-society-a2433',
    storageBucket: 'digital-society-a2433.appspot.com',
    iosClientId: '549657351342-ei1r3vkr8erns8kvofq7tpmnrkrus0n7.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalsociety.RunnerTests',
  );
}
